"""Regression tests for all bug fixes and final targeted correction pass.

Covers:
1. Authentication:
   - public registration cannot create ADMIN
   - public registration cannot create DELIVERY_AGENT
   - login JWT has valid string sub
   - /auth/me succeeds using login-generated JWT
2. Notifications:
   - admin-created order & status flows schedule notification processing after commit
   - admin override queues and schedules notification processing
   - manual assignment notification flow is processed
   - auto-assignment notification flow is processed
3. Audit identity:
   - customer reschedule creates event with customer ID + CUSTOMER role (never ADMIN)
4. Auto-assignment failure:
   - no eligible agent does not fail reschedule
   - order remains CONFIRMED
   - failed auto-assignment does not create AGENT_ASSIGNED (creates AUTO_ASSIGNMENT_FAILED)
5. Exception handling:
   - unexpected auto-assignment exceptions are not swallowed
6. Admin filtering:
   - agent_id returns orders currently assigned to that agent
   - closed/historical assignments are excluded
7. Rate card & package validation:
   - future/expired rate cards ignored
   - zero/negative dimensions rejected
"""
import pytest
from decimal import Decimal
from datetime import datetime, timedelta
from unittest.mock import MagicMock
from fastapi.testclient import TestClient

from tests.conftest import get_auth_header
from app.models import (
    User, UserRole, Agent, AgentAvailability, AgentLocation,
    Order, OrderType, PaymentType, OrderStatus,
    DeliveryAttempt, DeliveryAttemptStatus, Assignment, AssignmentType,
    RateCardVersion, RateRule, CodRule, MovementType,
    TrackingEvent, TrackingEventType, Area, NotificationOutbox, NotificationChannel, NotificationStatus,
)
from app.pricing.engine import get_active_rate_card, PricingError, calculate_price
from app.orders.schemas import OrderCreate
from app.dispatch.engine import auto_assign_order, manual_assign_order, NoEligibleAgentException
from app.orders.service import reschedule_order, create_order


# ─────────────────────────────────────────────────────────────────────────────
# 1. Authentication
# ─────────────────────────────────────────────────────────────────────────────

class TestAuthenticationSecurity:
    """Authentication and role enforcement tests."""

    def test_registration_without_role_creates_customer(self, client: TestClient, db_session):
        """Standard registration creates a CUSTOMER account."""
        resp = client.post("/auth/register", json={
            "email": "newuser@example.com",
            "password": "secretpassword",
            "full_name": "New User",
        })
        assert resp.status_code == 201, resp.text
        data = resp.json()
        assert data["role"] == "CUSTOMER"

    def test_registration_with_admin_role_still_creates_customer(self, client: TestClient, db_session):
        """Even if role=ADMIN is sent, public registration creates a CUSTOMER account."""
        resp = client.post("/auth/register", json={
            "email": "attacker@example.com",
            "password": "secretpassword",
            "full_name": "Attacker",
            "role": "ADMIN",
        })
        if resp.status_code == 201:
            assert resp.json()["role"] == "CUSTOMER"
        else:
            assert resp.status_code in (201, 422)

    def test_registration_with_delivery_agent_role_still_creates_customer(self, client: TestClient, db_session):
        """Even if role=DELIVERY_AGENT is sent, public registration creates a CUSTOMER account."""
        resp = client.post("/auth/register", json={
            "email": "fakeagent@example.com",
            "password": "secretpassword",
            "full_name": "Fake Agent",
            "role": "DELIVERY_AGENT",
        })
        if resp.status_code == 201:
            assert resp.json()["role"] == "CUSTOMER"
        else:
            assert resp.status_code in (201, 422)

    def test_login_returns_token_with_string_sub_and_auth_me_succeeds(self, seeded_client):
        """POST /auth/login returns a valid JWT with string sub, and GET /auth/me succeeds."""
        client, db = seeded_client
        # Login as seeded customer
        resp = client.post("/auth/login", json={
            "email": "cust@test.com",
            "password": "pass",
        })
        assert resp.status_code == 200, resp.text
        token_data = resp.json()
        assert "access_token" in token_data

        token = token_data["access_token"]
        # Verify /auth/me using the token generated by /auth/login
        me_resp = client.get("/auth/me", headers={"Authorization": f"Bearer {token}"})
        assert me_resp.status_code == 200, me_resp.text
        me_data = me_resp.json()
        assert me_data["email"] == "cust@test.com"
        assert me_data["role"] == "CUSTOMER"


# ─────────────────────────────────────────────────────────────────────────────
# 2. Notifications & Background Tasks
# ─────────────────────────────────────────────────────────────────────────────

class TestNotificationProcessing:
    """Notification creation and background processing tests."""

    def test_admin_create_order_queues_notification(self, seeded_client):
        """Admin creating an order queues a status_change notification in the outbox."""
        client, db = seeded_client
        admin = db.query(User).filter(User.role == UserRole.ADMIN).first()
        cust = db.query(User).filter(User.role == UserRole.CUSTOMER).first()
        headers = get_auth_header(admin)

        resp = client.post("/admin/orders", json={
            "customer_id": cust.id,
            "pickup_address": "JP Nagar",
            "pickup_postal_code": "560078",
            "drop_address": "Jayanagar",
            "drop_postal_code": "560041",
            "length": "10", "breadth": "10", "height": "10",
            "actual_weight": "2",
            "order_type": "B2C",
            "payment_type": "PREPAID",
        }, headers=headers)
        assert resp.status_code == 201, resp.text
        order_id = resp.json()["id"]

        db.expire_all()
        notifications = db.query(NotificationOutbox).filter(NotificationOutbox.order_id == order_id).all()
        assert len(notifications) > 0

    def test_admin_override_queues_notification(self, seeded_client):
        """Admin override status creates outbox notification."""
        client, db = seeded_client
        admin = db.query(User).filter(User.role == UserRole.ADMIN).first()
        cust = db.query(User).filter(User.role == UserRole.CUSTOMER).first()

        order = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            drop_address="B", drop_postal_code="560041",
            length=Decimal("5"), breadth=Decimal("5"), height=Decimal("5"),
            actual_weight=Decimal("1"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.CREATED,
        )
        db.add(order)
        db.commit()

        headers = get_auth_header(admin)
        resp = client.post(f"/admin/orders/{order.id}/override-status", json={
            "new_status": "CONFIRMED",
            "reason": "Customer called support",
        }, headers=headers)
        assert resp.status_code == 200, resp.text

        db.expire_all()
        notifs = db.query(NotificationOutbox).filter(NotificationOutbox.order_id == order.id).all()
        assert len(notifs) > 0
        assert any("CONFIRMED" in n.payload for n in notifs)

    def test_manual_and_auto_assign_notification_flow(self, seeded_client):
        """Manual and auto assignment queue notification events."""
        client, db = seeded_client
        admin = db.query(User).filter(User.role == UserRole.ADMIN).first()
        cust = db.query(User).filter(User.role == UserRole.CUSTOMER).first()
        area = db.query(Area).filter(Area.postal_code == "560078").first()

        order = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            pickup_area_id=area.id, pickup_zone_id=area.zone_id,
            drop_address="B", drop_postal_code="560041",
            length=Decimal("5"), breadth=Decimal("5"), height=Decimal("5"),
            actual_weight=Decimal("1"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.CONFIRMED,
        )
        db.add(order)
        db.commit()

        headers = get_auth_header(admin)
        resp = client.post(f"/admin/orders/{order.id}/auto-assign", headers=headers)
        assert resp.status_code == 200, resp.text

        db.expire_all()
        notifs = db.query(NotificationOutbox).filter(NotificationOutbox.order_id == order.id).all()
        assert any("ASSIGNED" in n.payload for n in notifs)


# ─────────────────────────────────────────────────────────────────────────────
# 3. Audit Identity & Actor Consistency
# ─────────────────────────────────────────────────────────────────────────────

class TestAuditIdentityConsistency:
    """Audit history must accurately reflect actor identity and role."""

    def test_customer_reschedule_uses_customer_role(self, seeded_db):
        """Customer-triggered reschedule auto-assignment uses customer ID + CUSTOMER role, never ADMIN."""
        area = seeded_db.query(Area).filter(Area.postal_code == "560078").first()
        cust = seeded_db.query(User).filter(User.role == UserRole.CUSTOMER).first()

        order = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            pickup_area_id=area.id, pickup_zone_id=area.zone_id,
            drop_address="B", drop_postal_code="560041",
            length=Decimal("10"), breadth=Decimal("10"), height=Decimal("10"),
            actual_weight=Decimal("2"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.AWAITING_RESCHEDULE,
        )
        seeded_db.add(order)
        seeded_db.flush()

        failed_attempt = DeliveryAttempt(
            order_id=order.id, attempt_number=1, status=DeliveryAttemptStatus.FAILED,
        )
        seeded_db.add(failed_attempt)
        seeded_db.commit()

        reschedule_order(seeded_db, order, cust.id, reason="Retry tomorrow")
        seeded_db.expire_all()

        events = seeded_db.query(TrackingEvent).filter(TrackingEvent.order_id == order.id).all()
        for ev in events:
            if ev.actor_user_id == cust.id:
                assert ev.actor_role == UserRole.CUSTOMER, \
                    f"Customer ID {cust.id} must never be recorded with ADMIN role! Got {ev.actor_role}"


# ─────────────────────────────────────────────────────────────────────────────
# 4. Auto-Assignment Failure & Exception Handling
# ─────────────────────────────────────────────────────────────────────────────

class TestAutoAssignmentFailure:
    """Handling no-agent conditions and unexpected exception propagation."""

    def test_no_agent_reschedule_emits_auto_assignment_failed_event(self, db_session):
        """When no eligible agent exists, reschedule succeeds, order stays CONFIRMED, and AUTO_ASSIGNMENT_FAILED event is recorded."""
        from app.models import Zone, Area, User, CustomerProfile
        from app.dependencies import get_password_hash

        z = Zone(name="Zone A", description="")
        db_session.add(z)
        db_session.flush()

        a = Area(name="Area A", postal_code="111111", zone_id=z.id, latitude=12.0, longitude=77.0)
        db_session.add(a)
        db_session.flush()

        cust_user = User(
            email="c@c.com", hashed_password=get_password_hash("pass"),
            full_name="Cust", role=UserRole.CUSTOMER,
        )
        db_session.add(cust_user)
        db_session.flush()
        db_session.add(CustomerProfile(user_id=cust_user.id))

        order = Order(
            customer_id=cust_user.id,
            pickup_address="A", pickup_postal_code="111111",
            pickup_area_id=a.id, pickup_zone_id=z.id,
            drop_address="B", drop_postal_code="111111",
            length=Decimal("10"), breadth=Decimal("10"), height=Decimal("10"),
            actual_weight=Decimal("2"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.AWAITING_RESCHEDULE,
        )
        db_session.add(order)
        db_session.flush()

        failed = DeliveryAttempt(
            order_id=order.id, attempt_number=1, status=DeliveryAttemptStatus.FAILED,
        )
        db_session.add(failed)
        db_session.commit()

        reschedule_order(db=db_session, order=order, customer_id=cust_user.id, reason="Retry")
        db_session.expire_all()
        db_session.refresh(order)

        # Order remains CONFIRMED
        assert order.current_status == OrderStatus.CONFIRMED

        # Tracking event must NOT be AGENT_ASSIGNED; it must be AUTO_ASSIGNMENT_FAILED
        events = db_session.query(TrackingEvent).filter(TrackingEvent.order_id == order.id).all()
        event_types = [e.event_type for e in events]
        assert TrackingEventType.AGENT_ASSIGNED not in event_types, "Must NOT emit AGENT_ASSIGNED when assignment failed!"
        assert TrackingEventType.AUTO_ASSIGNMENT_FAILED in event_types, "Must emit AUTO_ASSIGNMENT_FAILED on failure"

    def test_unexpected_exceptions_in_auto_assign_are_not_swallowed(self, seeded_db, monkeypatch):
        """Unexpected programming or DB errors in auto_assign_order must propagate, not be caught as no-agent."""
        area = seeded_db.query(Area).filter(Area.postal_code == "560078").first()
        cust = seeded_db.query(User).filter(User.role == UserRole.CUSTOMER).first()

        order = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            pickup_area_id=area.id, pickup_zone_id=area.zone_id,
            drop_address="B", drop_postal_code="560041",
            length=Decimal("10"), breadth=Decimal("10"), height=Decimal("10"),
            actual_weight=Decimal("2"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.AWAITING_RESCHEDULE,
        )
        seeded_db.add(order)
        seeded_db.flush()

        failed = DeliveryAttempt(
            order_id=order.id, attempt_number=1, status=DeliveryAttemptStatus.FAILED,
        )
        seeded_db.add(failed)
        seeded_db.commit()

        # Monkeypatch auto_assign_order to raise an unexpected ValueError
        import app.dispatch.engine
        def mock_broken_auto_assign(*args, **kwargs):
            raise RuntimeError("Unexpected Database Crash!")

        monkeypatch.setattr(app.dispatch.engine, "auto_assign_order", mock_broken_auto_assign)

        with pytest.raises(RuntimeError, match="Unexpected Database Crash!"):
            reschedule_order(db=seeded_db, order=order, customer_id=cust.id, reason="Retry")


# ─────────────────────────────────────────────────────────────────────────────
# 5. Admin Agent Filtering Semantics
# ─────────────────────────────────────────────────────────────────────────────

class TestAdminAgentFilteringSemantics:
    """Admin order list agent_id filter must return active assignments only."""

    def test_agent_filter_returns_only_active_assignments(self, seeded_client):
        """Historical/closed assignments are excluded from GET /admin/orders?agent_id=X."""
        client, db = seeded_client
        area = db.query(Area).filter(Area.postal_code == "560078").first()
        cust = db.query(User).filter(User.role == UserRole.CUSTOMER).first()
        admin = db.query(User).filter(User.role == UserRole.ADMIN).first()
        agent_users = db.query(User).filter(User.role == UserRole.DELIVERY_AGENT).all()
        agent1 = db.query(Agent).filter(Agent.user_id == agent_users[0].id).first()

        # Order 1: currently assigned to agent1 (unassigned_at IS NULL)
        o1 = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            pickup_area_id=area.id, pickup_zone_id=area.zone_id,
            drop_address="B", drop_postal_code="560041",
            length=Decimal("5"), breadth=Decimal("5"), height=Decimal("5"),
            actual_weight=Decimal("1"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.ASSIGNED,
        )
        db.add(o1)
        db.flush()
        att1 = DeliveryAttempt(order_id=o1.id, attempt_number=1, status=DeliveryAttemptStatus.ASSIGNED)
        db.add(att1)
        db.flush()
        as1 = Assignment(order_id=o1.id, delivery_attempt_id=att1.id, agent_id=agent1.id, assignment_type=AssignmentType.MANUAL, unassigned_at=None)
        db.add(as1)

        # Order 2: previously assigned to agent1, but closed/unassigned (unassigned_at IS NOT NULL)
        o2 = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            pickup_area_id=area.id, pickup_zone_id=area.zone_id,
            drop_address="B", drop_postal_code="560041",
            length=Decimal("5"), breadth=Decimal("5"), height=Decimal("5"),
            actual_weight=Decimal("1"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.DELIVERED,
        )
        db.add(o2)
        db.flush()
        att2 = DeliveryAttempt(order_id=o2.id, attempt_number=1, status=DeliveryAttemptStatus.DELIVERED)
        db.add(att2)
        db.flush()
        as2 = Assignment(order_id=o2.id, delivery_attempt_id=att2.id, agent_id=agent1.id, assignment_type=AssignmentType.MANUAL, unassigned_at=datetime.utcnow())
        db.add(as2)

        db.commit()

        headers = get_auth_header(admin)
        resp = client.get(f"/admin/orders?agent_id={agent1.id}", headers=headers)
        assert resp.status_code == 200, resp.text
        data = resp.json()
        order_ids = [o["id"] for o in data["orders"]]

        assert o1.id in order_ids, "Currently assigned order o1 must be in agent filter results"
        assert o2.id not in order_ids, "Closed/historical assignment o2 must be EXCLUDED from active agent filter results"


# ─────────────────────────────────────────────────────────────────────────────
# 6. Rate Card & Dimension Validation
# ─────────────────────────────────────────────────────────────────────────────

class TestRateCardAndValidation:
    """Rate card date filtering and dimension constraint checks."""

    def test_future_and_expired_rate_cards_ignored(self, seeded_db):
        """Future and expired cards are ignored by get_active_rate_card."""
        future_card = RateCardVersion(
            name="Future Card", effective_from=datetime.utcnow() + timedelta(days=30), is_active=True,
        )
        expired_card = RateCardVersion(
            name="Expired Card", effective_from=datetime.utcnow() - timedelta(days=60), effective_to=datetime.utcnow() - timedelta(days=1), is_active=True,
        )
        seeded_db.add_all([future_card, expired_card])
        seeded_db.commit()

        active = get_active_rate_card(seeded_db)
        assert active.name not in ("Future Card", "Expired Card")

    def test_zero_and_negative_dimensions_rejected(self, seeded_client):
        """Pydantic rejects zero or negative package dimensions."""
        client, db = seeded_client
        cust = db.query(User).filter(User.role == UserRole.CUSTOMER).first()
        headers = get_auth_header(cust)

        base_payload = {
            "pickup_address": "A", "pickup_postal_code": "560078",
            "drop_address": "B", "drop_postal_code": "560041",
            "length": "10", "breadth": "10", "height": "10", "actual_weight": "2",
            "order_type": "B2C", "payment_type": "PREPAID",
        }

        # Test zero length
        p1 = dict(base_payload, length="0")
        assert client.post("/orders", json=p1, headers=headers).status_code == 422

        # Test negative weight
        p2 = dict(base_payload, actual_weight="-1")
        assert client.post("/orders", json=p2, headers=headers).status_code == 422


# ─────────────────────────────────────────────────────────────────────────────
# 7. Notification Recipients & Contact Validation
# ─────────────────────────────────────────────────────────────────────────────

class TestNotificationRecipientsAndChannels:
    """Notification contact resolution and channel queuing tests."""

    def test_status_change_queues_email_and_sms_with_actual_contact_details(self, db_session):
        """Status change queues both EMAIL and SMS using actual customer email and phone."""
        from app.dependencies import get_password_hash
        from app.tracking.service import create_status_change_event_and_notification
        from app.notifications.service import process_pending_notifications

        cust = User(
            email="actualcust@domain.com",
            hashed_password=get_password_hash("pass"),
            full_name="Actual Customer",
            phone="9876543210",
            role=UserRole.CUSTOMER,
        )
        db_session.add(cust)
        db_session.flush()

        order = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            drop_address="B", drop_postal_code="560041",
            length=Decimal("5"), breadth=Decimal("5"), height=Decimal("5"),
            actual_weight=Decimal("1"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.CREATED,
        )
        db_session.add(order)
        db_session.commit()

        create_status_change_event_and_notification(
            db=db_session,
            order=order,
            event_type=TrackingEventType.ORDER_CONFIRMED,
            previous_status="CREATED",
            new_status="CONFIRMED",
        )
        db_session.commit()

        notifs = db_session.query(NotificationOutbox).filter(NotificationOutbox.order_id == order.id).all()
        assert len(notifs) == 2, f"Expected 2 outbox entries (EMAIL + SMS), got {len(notifs)}"

        channels = {n.channel for n in notifs}
        assert NotificationChannel.EMAIL in channels
        assert NotificationChannel.SMS in channels

        email_notif = next(n for n in notifs if n.channel == NotificationChannel.EMAIL)
        sms_notif = next(n for n in notifs if n.channel == NotificationChannel.SMS)

        import json
        email_payload = json.loads(email_notif.payload)
        sms_payload = json.loads(sms_notif.payload)

        assert email_payload.get("email") == "actualcust@domain.com"
        assert sms_payload.get("phone") == "9876543210"

        # Process outbox and verify no placeholders used
        results = process_pending_notifications(db_session)
        assert results["sent"] == 2

    def test_customer_without_phone_does_not_generate_bogus_sms(self, db_session):
        """Customer without phone queues EMAIL and skips SMS cleanly without dummy number."""
        from app.dependencies import get_password_hash
        from app.tracking.service import create_status_change_event_and_notification
        from app.notifications.service import process_pending_notifications

        cust = User(
            email="nophone@domain.com",
            hashed_password=get_password_hash("pass"),
            full_name="No Phone Customer",
            phone=None,
            role=UserRole.CUSTOMER,
        )
        db_session.add(cust)
        db_session.flush()

        order = Order(
            customer_id=cust.id,
            pickup_address="A", pickup_postal_code="560078",
            drop_address="B", drop_postal_code="560041",
            length=Decimal("5"), breadth=Decimal("5"), height=Decimal("5"),
            actual_weight=Decimal("1"),
            order_type=OrderType.B2C, payment_type=PaymentType.PREPAID,
            current_status=OrderStatus.CREATED,
        )
        db_session.add(order)
        db_session.commit()

        create_status_change_event_and_notification(
            db=db_session,
            order=order,
            event_type=TrackingEventType.ORDER_CONFIRMED,
            previous_status="CREATED",
            new_status="CONFIRMED",
        )
        db_session.commit()

        notifs = db_session.query(NotificationOutbox).filter(NotificationOutbox.order_id == order.id).all()
        # SMS should not be queued when customer has no phone
        sms_notifs = [n for n in notifs if n.channel == NotificationChannel.SMS]
        assert len(sms_notifs) == 0, "SMS must NOT be queued for customers without a phone number"

        results = process_pending_notifications(db_session)
        assert results["sent"] == 1

    def test_providers_reject_missing_recipient_without_placeholders(self):
        """SmtpEmailProvider and TwilioSmsProvider raise ValueError when recipient contact is missing (no placeholders)."""
        from app.notifications.providers import SmtpEmailProvider, TwilioSmsProvider

        email_provider = SmtpEmailProvider()
        with pytest.raises(ValueError, match="Recipient email address is missing"):
            email_provider.send("EMAIL", "template", {})

        sms_provider = TwilioSmsProvider()
        with pytest.raises(ValueError, match="Recipient phone number is missing"):
            sms_provider.send("SMS", "template", {})

