"""initial_schema

Revision ID: 0ef2dd0b06cf
Revises: 
Create Date: 2026-08-24 00:36:00.702895

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef2dd0b06cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pickup_zone_id', sa.Integer(), nullable=False),
    sa.Column('drop_zone_id', sa.Integer(), nullable=False),
    sa.Column('actual_weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volumetric_weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('billable_weight', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('movement_type', sa.Enum('INTRA_ZONE', 'INTER_ZONE', name='movementtype'), nullable=False),
    sa.Column('rate_card_version_id', sa.Integer(), nullable=False),
    sa.Column('rate_rule_id', sa.Integer(), nullable=False),
    sa.Column('base_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cod_surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drop_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ),
    sa.ForeignKeyConstraint(['rate_rule_id'], ['rate_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('order_price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_price_snapshots_id'), ['id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_postal_code', sa.String(length=10), nullable=False),
    sa.Column('pickup_area_id', sa.Integer(), nullable=True),
    sa.Column('pickup_zone_id', sa.Integer(), nullable=True),
    sa.Column('drop_address', sa.Text(), nullable=False),
    sa.Column('drop_postal_code', sa.String(length=10), nullable=False),
    sa.Column('drop_area_id', sa.Integer(), nullable=True),
    sa.Column('drop_zone_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('breadth', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('height', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_type', sa.Enum('B2B', 'B2C', name='ordertype'), nullable=False),
    sa.Column('payment_type', sa.Enum('PREPAID', 'COD', name='paymenttype'), nullable=False),
    sa.Column('current_status', sa.Enum('CREATED', 'CONFIRMED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', 'AWAITING_RESCHEDULE', name='orderstatus'), nullable=False),
    sa.Column('price_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['drop_area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['drop_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['pickup_area_id'], ['areas.id'], ),
    sa.ForeignKeyConstraint(['pickup_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['order_price_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)

    op.create_table('rate_card_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_card_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_card_versions_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('CUSTOMER', 'DELIVERY_AGENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_id'), ['id'], unique=False)

    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'UNAVAILABLE', 'INACTIVE', name='agentavailability'), nullable=False),
    sa.Column('current_zone_id', sa.Integer(), nullable=True),
    sa.Column('active_delivery_count', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_deliveries', sa.Integer(), nullable=False),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_zone_id'], ['zones.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_id'), ['id'], unique=False)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_areas_postal_code'), ['postal_code'], unique=True)

    op.create_table('cod_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_card_version_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('B2B', 'B2C', name='ordertype'), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('surcharge >= 0', name='ck_cod_rules_surcharge'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cod_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cod_rules_id'), ['id'], unique=False)

    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('default_pickup_address', sa.Text(), nullable=True),
    sa.Column('default_pickup_postal_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_profiles_id'), ['id'], unique=False)

    op.create_table('delivery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'FAILED', name='deliveryattemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_attempt_number_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'attempt_number', name='uq_order_attempt')
    )
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_attempts_order_id'), ['order_id'], unique=False)

    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notificationchannel'), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_outbox_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_outbox_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_outbox_status'), ['status'], unique=False)

    op.create_table('rate_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_card_version_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('B2B', 'B2C', name='ordertype'), nullable=False),
    sa.Column('movement_type', sa.Enum('INTRA_ZONE', 'INTER_ZONE', name='movementtype'), nullable=False),
    sa.Column('min_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_weight', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_kg_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('base_charge >= 0', name='ck_rate_rules_base_charge'),
    sa.CheckConstraint('max_weight > min_weight', name='ck_rate_rules_max_weight'),
    sa.CheckConstraint('min_weight >= 0', name='ck_rate_rules_min_weight'),
    sa.CheckConstraint('per_kg_charge >= 0', name='ck_rate_rules_per_kg_charge'),
    sa.ForeignKeyConstraint(['rate_card_version_id'], ['rate_card_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_rules_id'), ['id'], unique=False)

    op.create_table('agent_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_locations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_locations_id'), ['id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_attempt_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.Enum('MANUAL', 'AUTO', name='assignmenttype'), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('score_explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_attempt_id'], ['delivery_attempts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_order_id'), ['order_id'], unique=False)

    op.create_table('reschedule_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('failed_attempt_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reschedulestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['failed_attempt_id'], ['delivery_attempts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reschedule_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reschedule_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reschedule_requests_order_id'), ['order_id'], unique=False)

    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_attempt_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('ORDER_CREATED', 'ORDER_CONFIRMED', 'AGENT_ASSIGNED', 'AGENT_REASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERY_FAILED', 'RESCHEDULE_REQUESTED', 'NEW_ATTEMPT_CREATED', 'DELIVERED', 'ADMIN_OVERRIDE', name='trackingeventtype'), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.Enum('CUSTOMER', 'DELIVERY_AGENT', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_attempt_id'], ['delivery_attempts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracking_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracking_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracking_events_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracking_events_order_id'))
        batch_op.drop_index(batch_op.f('ix_tracking_events_id'))

    op.drop_table('tracking_events')
    with op.batch_alter_table('reschedule_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reschedule_requests_order_id'))
        batch_op.drop_index(batch_op.f('ix_reschedule_requests_id'))

    op.drop_table('reschedule_requests')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_order_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_agent_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('agent_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_locations_id'))
        batch_op.drop_index(batch_op.f('ix_agent_locations_agent_id'))

    op.drop_table('agent_locations')
    with op.batch_alter_table('rate_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_rules_id'))

    op.drop_table('rate_rules')
    with op.batch_alter_table('notification_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_notification_outbox_order_id'))
        batch_op.drop_index(batch_op.f('ix_notification_outbox_id'))

    op.drop_table('notification_outbox')
    with op.batch_alter_table('delivery_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_attempts_id'))

    op.drop_table('delivery_attempts')
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_profiles_id'))

    op.drop_table('customer_profiles')
    with op.batch_alter_table('cod_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cod_rules_id'))

    op.drop_table('cod_rules')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_postal_code'))
        batch_op.drop_index(batch_op.f('ix_areas_id'))

    op.drop_table('areas')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_id'))

    op.drop_table('agents')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_id'))

    op.drop_table('zones')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('rate_card_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_card_versions_id'))

    op.drop_table('rate_card_versions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_current_status'))

    op.drop_table('orders')
    with op.batch_alter_table('order_price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_price_snapshots_id'))

    op.drop_table('order_price_snapshots')
    # ### end Alembic commands ###
